### ISSUE TITLE
'DataFrame' object has no attribute 'append'. Did you mean: '_append'?

### ISSUE THREAD

**Issue by cavebutter** [fdebellabre/tournament-scheduler#1]
When running the example provided in the docs:
```
import numpy as np
import pandas as pd
nteams = 10
nfields = 3
bestfields = 1
teams = ['Team ' + str(z+1) for z in range(nteams)]
games = scheduler.get_best_schedule(teams, nfields, bestfields)
```
I get the traceback:
'''
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2022.3.2\plugins\python\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "C:\Users\nerd\OneDrive - The Canton Group\dev\schedule\venv\lib\site-packages\scheduler\schedule_generation.py", line 96, in get_best_schedule
    games, perfect_matches, okay = gg.get_best_match(teams, nfield, nbest)
  File "C:\Users\nerd\OneDrive - The Canton Group\dev\schedule\venv\lib\site-packages\scheduler\games_generation.py", line 128, in get_best_match
    perfect_matches = np.sum(check_list_quality(games, nfield))
  File "C:\Users\nerd\OneDrive - The Canton Group\dev\schedule\venv\lib\site-packages\scheduler\games_generation.py", line 96, in check_list_quality
    dfboth = dfhome.append(dfaway).reset_index()
  File "C:\Users\nerd\OneDrive - The Canton Group\dev\schedule\venv\lib\site-packages\pandas\core\generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
'''

**Comment by fdebellabre** [comment]
I updated the requirements to use `pandas==1.*`. The code should run fine now.
